version:  '3.8'

networks:
  epg_proxy_net:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    ports:
      - "4400:80"
    networks:
      - epg_proxy_net 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./whitelisted_channels.txt:/app/whitelisted_channels.txt
    depends_on:
      - epg_proxy

  epg_proxy:
    build: .
    networks:
      - epg_proxy_net
    ports:
      - "8080:8080"

  mock_server:
    build: 
      context: .
      dockerfile: Dockerfile.mock
    networks:
      - epg_proxy_net
    ports:
      - "9090:9090"
    depends_on:
      - epg_proxy
